# Generated by Django 5.1.15 on 2026-08-24 00:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_auth', '0001_initial'),
        ('ordenes_trabajo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoProyecto',
            fields=[
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('concepto_hito', models.CharField(choices=[('Anticipo_50', 'Anticipo 50%'), ('Avance_30', 'Avance 30%'), ('Saldo_Entrega_20', 'Saldo Entrega 20%'), ('Otro', 'Otro Abono / Pago Parcial')], max_length=50)),
                ('monto_pago', models.DecimalField(decimal_places=2, max_digits=12)),
                ('medio_pago', models.CharField(choices=[('Transferencia', 'Transferencia Bancaria'), ('Efectivo', 'Efectivo'), ('Cheque', 'Cheque'), ('Tarjeta', 'Tarjeta Débito / Crédito')], max_length=50)),
                ('fecha_pago', models.DateField(default=django.utils.timezone.now)),
                ('comprobante_referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_set', to='core_auth.empresa')),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pagos_recibidos', to='ordenes_trabajo.proyecto')),
                ('id_usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago / Abono de Proyecto',
                'verbose_name_plural': 'Pagos / Abonos de Proyectos',
                'db_table': 'pagos_proyecto',
                'ordering': ['-fecha_pago', '-fecha_registro'],
            },
        ),
    ]
