# Generated by Django 5.1.15 on 2026-08-23 22:51

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=255)),
                ('rut_o_identificacion', models.CharField(blank=True, max_length=50, null=True)),
                ('correo_general', models.EmailField(blank=True, max_length=255, null=True)),
                ('telefono_general', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_contacto', models.CharField(max_length=255)),
                ('correo_contacto', models.EmailField(blank=True, max_length=255, null=True)),
                ('telefono_contacto', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('comuna', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('Tableros', 'Tableros'), ('Maderas', 'Maderas'), ('Quincalleria', 'Quincallería'), ('Insumos', 'Insumos')], max_length=100)),
                ('unidad_medida', models.CharField(max_length=50)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('porcentaje_merma_defecto', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'db_table': 'materiales',
                'ordering': ['categoria', 'nombre'],
            },
        ),
    ]
