# Generated by Django 5.1.15 on 2026-08-23 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion_base', '0001_initial'),
        ('core_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='id_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_set', to='core_auth.empresa'),
        ),
        migrations.AddField(
            model_name='material',
            name='id_empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_set', to='core_auth.empresa'),
        ),
    ]
