# Generated by Django 5.1.15 on 2026-08-24 21:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion_base', '0002_initial'),
        ('core_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialGlobal',
            fields=[
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku_proveedor', models.CharField(db_index=True, max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('Tableros', 'Tableros'), ('Maderas', 'Maderas'), ('Quincalleria', 'Quincallería'), ('Insumos', 'Insumos')], max_length=100)),
                ('unidad_medida', models.CharField(max_length=50)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('proveedor', models.CharField(default='Imperial', max_length=100)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Material Global',
                'verbose_name_plural': 'Materiales Globales',
                'db_table': 'materiales_globales',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='material',
            name='actualizacion_automatica',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='material',
            name='sku_proveedor',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='material_global',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiales_talleres', to='configuracion_base.materialglobal'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.UniqueConstraint(condition=models.Q(('sku_proveedor__isnull', False)), fields=('id_empresa', 'sku_proveedor'), name='unique_tenant_sku'),
        ),
    ]
