# Generated by Django 5.1.15 on 2026-08-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion_base', '0004_materialglobal_sku_interno'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Notas / Información de Contacto'),
        ),
        migrations.AddField(
            model_name='material',
            name='proveedor',
            field=models.CharField(default='Imperial', max_length=100, verbose_name='Proveedor'),
        ),
    ]
