# Generated by Django 5.1.15 on 2026-09-02 00:18

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion_base', '0005_material_observaciones_material_proveedor'),
        ('core_auth', '0001_initial'),
        ('ordenes_trabajo', '0002_itemproyecto_cantidad_descontada_stock_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='stock_actual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Stock Actual en Bodega'),
        ),
        migrations.AddField(
            model_name='material',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Stock Mínimo de Alerta'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_movimiento', models.CharField(choices=[('INGRESO_INICIAL', 'Ingreso Inicial / Carga de Stock'), ('COMPRA_BODEGA', 'Compra para Stock en Bodega'), ('DESCUENTO_OT', 'Descuento por Asignación a Orden de Trabajo'), ('AJUSTE_MANUAL', 'Ajuste Manual de Inventario'), ('DEVOLUCION', 'Devolución de Proyecto a Bodega')], max_length=50)),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Positivo para entradas, Negativo para salidas', max_digits=10)),
                ('stock_resultante', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_set', to='core_auth.empresa')),
                ('id_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='configuracion_base.material')),
                ('id_proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to='ordenes_trabajo.proyecto')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='movimientos_inventario_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'db_table': 'movimientos_inventario',
                'ordering': ['-fecha_movimiento'],
            },
        ),
    ]
