# Generated by Django 5.1.15 on 2026-09-02 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion_base', '0006_material_stock_actual_material_stock_minimo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='proveedor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Proveedor'),
        ),
    ]
