# Generated by Django 5.1.15 on 2026-09-08 14:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion_base', '0007_alter_material_proveedor'),
        ('core_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razon_social', models.CharField(max_length=255, verbose_name='Razón Social / Nombre')),
                ('rut_o_identificacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='RUT / ID Fiscal')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('comuna', models.CharField(blank=True, max_length=100, null=True, verbose_name='Comuna')),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('nombre_contacto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Persona de Contacto')),
                ('telefono_contacto', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('correo_contacto', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo Electrónico')),
                ('banco_nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco')),
                ('tipo_cuenta', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Cuenta')),
                ('numero_cuenta', models.CharField(blank=True, max_length=50, null=True, verbose_name='N° de Cuenta')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones / Notas')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_set', to='core_auth.empresa')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedores',
                'ordering': ['razon_social'],
            },
        ),
    ]
