# Generated by Django 5.1.15 on 2026-09-08 20:58

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion_base', '0008_proveedor'),
        ('core_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_banco', models.CharField(max_length=150, verbose_name='Nombre del Banco')),
                ('codigo_sbif', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código SBIF / Identificador')),
                ('numero_cuenta', models.CharField(blank=True, max_length=100, null=True, verbose_name='N° de Cuenta Corriente / Vista')),
                ('tipo_cuenta', models.CharField(default='Cuenta Corriente', max_length=50, verbose_name='Tipo de Cuenta')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_set', to='core_auth.empresa')),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'db_table': 'bancos',
                'ordering': ['nombre_banco'],
            },
        ),
        migrations.CreateModel(
            name='ServicioTarifa',
            fields=[
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(max_length=255, verbose_name='Nombre del Servicio')),
                ('categoria', models.CharField(choices=[('Flete_Traslado', 'Flete y Traslado'), ('Montaje_Obra', 'Montaje en Obra'), ('Instalacion_Especial', 'Instalación Especial / Eléctrica'), ('Subcontrato', 'Subcontrato / Servicio Tercero'), ('Otro', 'Otro Servicio')], default='Flete_Traslado', max_length=100, verbose_name='Categoría')),
                ('unidad_medida', models.CharField(default='Global', max_length=50, verbose_name='Unidad de Medida (Global, Día, Hora, Viaje)')),
                ('costo_base_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Costo Base Estimado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Notas / Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_set', to='core_auth.empresa')),
            ],
            options={
                'verbose_name': 'Servicio / Tarifa',
                'verbose_name_plural': 'Servicios / Tarifas',
                'db_table': 'servicios_tarifas',
                'ordering': ['categoria', 'nombre_servicio'],
            },
        ),
    ]
