# Generated by Django 5.1.15 on 2026-09-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion_base', '0009_banco_serviciotarifa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco',
            name='tipo_cuenta',
            field=models.CharField(choices=[('Cuenta Corriente', 'Cuenta Corriente'), ('Cuenta Vista', 'Cuenta Vista'), ('Cuenta Ahorro', 'Cuenta Ahorro'), ('Cuenta Nómina', 'Cuenta Nómina')], default='Cuenta Corriente', max_length=50, verbose_name='Tipo de Cuenta'),
        ),
    ]
