# Generated by Django 5.1.15 on 2026-09-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion_base', '0010_alter_banco_tipo_cuenta'),
        ('core_auth', '0002_alter_usuario_rol'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='banco',
            constraint=models.UniqueConstraint(condition=models.Q(('numero_cuenta__isnull', False), models.Q(('numero_cuenta', ''), _negated=True)), fields=('id_empresa', 'numero_cuenta'), name='unique_tenant_banco_numero_cuenta'),
        ),
    ]
