# Generated by Django 5.1.15 on 2026-08-23 22:51

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=255)),
                ('rut_o_identificacion', models.CharField(blank=True, max_length=50, null=True)),
                ('plan_suscripcion', models.CharField(choices=[('basico', 'Plan Básico Taller'), ('pro', 'Plan Pro Taller'), ('enterprise', 'Plan Enterprise')], default='basico', max_length=50)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresas',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('correo_electronico', models.EmailField(max_length=255, unique=True)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('superadmin_saas', 'Administrador SaaS Global'), ('dueno_taller', 'Dueño / Admin del Taller'), ('jefe_taller', 'Jefe de Taller'), ('operario', 'Operario'), ('montador', 'Montador'), ('compras', 'Compras'), ('disenador', 'Diseñador'), ('vendedor', 'Vendedor')], default='operario', max_length=50)),
                ('costo_hora', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('id_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='usuarios', to='core_auth.empresa')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='AuditoriaLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=100)),
                ('detalles', models.TextField(blank=True, null=True)),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_auditadas', to=settings.AUTH_USER_MODEL)),
                ('id_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to='core_auth.empresa')),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'db_table': 'auditoria_logs',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
