# Generated by Django 5.1.15 on 2026-09-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('superadmin_saas', 'Administrador SaaS Global'), ('dueno_taller', 'Dueño / Admin del Taller'), ('jefe_taller', 'Jefe de Taller'), ('operario', 'Operario'), ('administrativo', 'Administrativo'), ('compras', 'Compras'), ('disenador', 'Diseñador'), ('vendedor', 'Vendedor')], default='operario', max_length=50),
        ),
    ]
