# Generated by Django 5.1.15 on 2026-08-24 00:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_auth', '0001_initial'),
        ('ordenes_trabajo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaCompra',
            fields=[
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_factura', models.CharField(max_length=100)),
                ('proveedor', models.CharField(max_length=255)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now)),
                ('monto_total_neto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_set', to='core_auth.empresa')),
                ('id_usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='facturas_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Factura de Compra',
                'verbose_name_plural': 'Facturas de Compra',
                'db_table': 'facturas_compra',
                'ordering': ['-fecha_emision', '-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='GastoProyecto',
            fields=[
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('tipo_gasto', models.CharField(choices=[('Material', 'Material'), ('Ferreteria_Imprevista', 'Ferretería Imprevista'), ('Flete', 'Flete'), ('Subcontrato', 'Subcontrato')], max_length=50)),
                ('monto_neto_asignado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_gasto', models.DateTimeField(auto_now_add=True)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_set', to='core_auth.empresa')),
                ('id_factura_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_distribuidos', to='compras_gastos.facturacompra')),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='gastos', to='ordenes_trabajo.proyecto')),
                ('id_usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='gastos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gasto Distribuido a Proyecto',
                'verbose_name_plural': 'Gastos Distribuidos a Proyectos',
                'db_table': 'gastos_proyecto',
            },
        ),
        migrations.CreateModel(
            name='RegistroTiempo',
            fields=[
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('etapa', models.CharField(choices=[('Corte', 'Corte'), ('Armado', 'Armado'), ('Laca_Pintura', 'Laca y Pintura'), ('Montaje', 'Montaje')], max_length=100)),
                ('horas_trabajadas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_mano_obra_calculado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_set', to='core_auth.empresa')),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tiempos_registrados', to='ordenes_trabajo.proyecto')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='horas_computadas', to=settings.AUTH_USER_MODEL)),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tiempos_ingresados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Tiempo (MOD)',
                'verbose_name_plural': 'Registros de Tiempo (MOD)',
                'db_table': 'registros_tiempo',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.AddConstraint(
            model_name='facturacompra',
            constraint=models.UniqueConstraint(fields=('id_empresa', 'numero_factura', 'proveedor'), name='unique_factura_proveedor_per_tenant'),
        ),
    ]
