# Generated by Django 5.1.15 on 2026-08-25 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras_gastos', '0001_initial'),
        ('ordenes_trabajo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastoproyecto',
            name='id_item_proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='ordenes_trabajo.itemproyecto'),
        ),
    ]
