# Generated by Django 5.1.15 on 2026-09-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras_gastos', '0002_gastoproyecto_id_item_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacompra',
            name='banco_origen',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco / Institución'),
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='forma_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('TARJETA_DEBITO', 'Tarjeta de Débito'), ('TARJETA_CREDITO', 'Tarjeta de Crédito'), ('CHEQUE', 'Cheque'), ('CREDITO_PROVEEDOR', 'Crédito Proveedor / Cta. Corriente'), ('OTRO', 'Otro / Varios')], default='TRANSFERENCIA', max_length=50, verbose_name='Forma de Pago'),
        ),
    ]
