# Generated by Django 5.1.15 on 2026-09-08 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras_gastos', '0003_facturacompra_banco_origen_facturacompra_forma_pago'),
        ('configuracion_base', '0008_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacompra',
            name='id_proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_compra', to='configuracion_base.proveedor', verbose_name='Proveedor Registrado'),
        ),
        migrations.AlterField(
            model_name='facturacompra',
            name='proveedor',
            field=models.CharField(help_text='Nombre o razón social del proveedor', max_length=255),
        ),
    ]
