# Generated by Django 5.1.15 on 2026-09-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras_gastos', '0004_facturacompra_id_proveedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacompra',
            name='fecha_vencimiento_cheque',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Vencimiento Cheque / Plazo'),
        ),
    ]
