# Generated by Django 5.1.15 on 2026-09-08 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras_gastos', '0005_facturacompra_fecha_vencimiento_cheque'),
        ('configuracion_base', '0009_banco_serviciotarifa'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacompra',
            name='id_banco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_compra', to='configuracion_base.banco', verbose_name='Banco Registrado'),
        ),
        migrations.AlterField(
            model_name='facturacompra',
            name='banco_origen',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco / Institución Textual'),
        ),
    ]
