# Generated by Django 5.1.15 on 2026-09-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras_gastos', '0006_facturacompra_id_banco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacompra',
            name='numero_cheque',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='N° de Cheque'),
        ),
    ]
