# Generated by Django 5.1.15 on 2026-08-24 00:02

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion_base', '0002_initial'),
        ('core_auth', '0001_initial'),
        ('cotizador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_ot', models.CharField(max_length=50)),
                ('nombre_proyecto', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('planificado', 'Planificado'), ('corte', 'En Corte'), ('armado', 'En Armado'), ('laca_pintura', 'Laca y Pintura'), ('montaje', 'Montaje en Obra'), ('entregado', 'Entregado Conforme')], default='planificado', max_length=50)),
                ('precio_cotizado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('costo_presupuestado_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('margen_objetivo_pct', models.DecimalField(decimal_places=2, default=Decimal('35.00'), max_digits=5)),
                ('fecha_inicio_programada', models.DateField(blank=True, null=True)),
                ('fecha_inicio_real', models.DateField(blank=True, null=True)),
                ('fecha_fin_real', models.DateField(blank=True, null=True)),
                ('fecha_compromiso_entrega', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='proyectos', to='configuracion_base.cliente')),
                ('id_cotizacion_origen', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='proyectos_generados', to='cotizador.cotizacion')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_set', to='core_auth.empresa')),
            ],
            options={
                'verbose_name': 'Proyecto / Orden de Trabajo',
                'verbose_name_plural': 'Proyectos / Órdenes de Trabajo',
                'db_table': 'proyectos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ItemProyecto',
            fields=[
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('tipo_item', models.CharField(choices=[('Material', 'Material'), ('Mano_Obra', 'Mano de Obra'), ('Servicio_Tercero', 'Servicio Tercero'), ('Insumo', 'Insumo')], max_length=50)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal_costo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('agregado_rectificacion', models.BooleanField(default=False)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_set', to='core_auth.empresa')),
                ('id_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='configuracion_base.material')),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_produccion', to='ordenes_trabajo.proyecto')),
            ],
            options={
                'verbose_name': 'Ítem de Producción',
                'verbose_name_plural': 'Ítems de Producción',
                'db_table': 'items_proyecto',
            },
        ),
        migrations.AddConstraint(
            model_name='proyecto',
            constraint=models.UniqueConstraint(fields=('id_empresa', 'codigo_ot'), name='unique_ot_per_tenant'),
        ),
    ]
