# Generated by Django 5.1.15 on 2026-09-02 00:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes_trabajo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemproyecto',
            name='cantidad_descontada_stock',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cantidad resuelta desde stock de bodega', max_digits=10),
        ),
        migrations.AddField(
            model_name='itemproyecto',
            name='stock_descontado',
            field=models.BooleanField(default=False, help_text='Indica si ya se aplicó el descuento automático de inventario'),
        ),
    ]
