# Generated by Django 5.1.15 on 2026-08-24 00:02

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracion_base', '0002_initial'),
        ('core_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_cotizacion', models.CharField(max_length=50)),
                ('version', models.IntegerField(default=1)),
                ('titulo_propuesta', models.CharField(max_length=255)),
                ('costo_materiales_estimado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('costo_mano_obra_estimado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('costo_servicios_estimado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('costo_indirecto_cif_estimado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('costo_total_estimado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('margen_objetivo_pct', models.DecimalField(decimal_places=2, default=Decimal('35.00'), max_digits=5)),
                ('precio_venta_neto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada al Cliente'), ('aprobada', 'Aprobada (Convertida a OT)'), ('rechazada', 'Rechazada'), ('expirada', 'Expirada')], default='borrador', max_length=50)),
                ('dias_validez', models.IntegerField(default=15)),
                ('notas_condiciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cotizaciones', to='configuracion_base.cliente')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_set', to='core_auth.empresa')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'db_table': 'cotizaciones',
                'ordering': ['-fecha_creacion', 'version'],
            },
        ),
        migrations.CreateModel(
            name='ItemCotizacion',
            fields=[
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('tipo_item', models.CharField(choices=[('Material', 'Material'), ('Mano_Obra', 'Mano de Obra'), ('Servicio_Tercero', 'Servicio Tercero'), ('Insumo', 'Insumo')], max_length=50)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('porcentaje_merma_aplicado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('subtotal_costo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('id_cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cotizador.cotizacion')),
                ('id_empresa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='%(class)s_set', to='core_auth.empresa')),
                ('id_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='configuracion_base.material')),
            ],
            options={
                'verbose_name': 'Ítem de Cotización',
                'verbose_name_plural': 'Ítems de Cotización',
                'db_table': 'items_cotizacion',
            },
        ),
        migrations.AddConstraint(
            model_name='cotizacion',
            constraint=models.UniqueConstraint(fields=('id_empresa', 'numero_cotizacion', 'version'), name='unique_cotizacion_per_tenant'),
        ),
    ]
