# Generated by Django 5.1.15 on 2026-08-25 20:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_entrega_manual',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega Fija/Prometida'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_inicio_estimada',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Inicio Estimada'),
        ),
        migrations.AlterField(
            model_name='itemcotizacion',
            name='tipo_item',
            field=models.CharField(choices=[('Material', 'Material'), ('Mano_Obra', 'Mano de Obra'), ('Servicio_Tercero', 'Servicio Tercero'), ('Insumo', 'Insumo')], default='Material', max_length=50),
        ),
    ]
